# Generated by Django 2.2.16 on 2022-10-06 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20221004_2308'),
        ('reviews', '0003_auto_20221005_1708'),
    ]

    operations = [
    ]
